# Generated by Django 5.2.4 on 2025-08-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_id',
            new_name='student_id',
        ),
    ]
